import {
  Activity,
  AlertCircle,
  ArrowRight,
  BarChart3,
  Battery,
  Bell,
  Bot,
  Bug,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  Code,
  Cpu,
  ExternalLink,
  FileText,
  Gamepad,
  Gamepad2,
  Globe,
  HardDrive,
  Heart,
  Image,
  Info,
  Lightbulb,
  MessageCircle,
  Moon,
  Music,
  Palette,
  RefreshCw,
  Search,
  Server,
  Shield,
  Sparkles,
  Star,
  Sun,
  Tag,
  Ticket,
  Users,
  Wifi,
  Zap,
  Wrench,
} from 'lucide-react';

const ICONS = {
  activity: Activity,
  alert: AlertCircle,
  arrowright: ArrowRight,
  barchart3: BarChart3,
  bot: Bot,
  bug: Bug,
  calendar: Calendar,
  check: Check,
  checkcircle: CheckCircle,
  chevrondown: ChevronDown,
  chevronright: ChevronRight,
  code: Code,
  cpu: Cpu,
  external: ExternalLink,
  filetext: FileText,
  gamepad: Gamepad,
  gamepad2: Gamepad2,
  globe: Globe,
  harddrive: HardDrive,
  heart: Heart,
  image: Image,
  info: Info,
  lightbulb: Lightbulb,
  messagecircle: MessageCircle,
  moon: Moon,
  music: Music,
  palette: Palette,
  refreshcw: RefreshCw,
  search: Search,
  server: Server,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  tag: Tag,
  ticket: Ticket,
  users: Users,
  wifi: Wifi,
  zap: Zap,
  wrench: Wrench,
};

export const getIcon = (iconName) => {
  if (!iconName) return null;
  return ICONS[iconName.toString().toLowerCase()] || null;
};

export default ICONS;
